# Generated by Django 5.1.1 on 2024-10-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETAS', 'Planetas')], default='', max_length=100),
        ),
    ]
