# Generated by Django 5.1.1 on 2024-10-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
